### ISSUE TITLE
Deploying installs Polymer 1.2, but declarativewidgets are pegged at 1.1.x

### ISSUE THREAD

**Issue by jhpedemonte** [jupyter-incubator/dashboards#80]
When deploying a local dashboard, Polymer v1.2 is installed. But this breaks Urth channels (see jupyter-incubator/declarativewidgets#62). For that reason, the declarativewidgets devs have [pegged their installs at v1.1.x](https://github.com/jupyter-incubator/declarativewidgets/commit/6b174e9bc24b381d6503e91b6785c35fabdf2335). We should use the same versions that they define in their bower.json.

(Hey :cow:, let's :meat_on_bone: @ :clock930:)

**Comment by lbustelo** [comment]
I just merged in a fix that allows us to move to polymer 1.2. I think this can be closed.

**Comment by parente** [comment]
Well, we still have the problem that we run bower install when packaging the notebook as a dashboard. If that bower install manages to pull down different versions from what was originally downloaded, the dashboard will be busted in unexpected ways. We should try to use whatever is already installed in the Jupyter server instead of letting bower pull down newer versions if possible.

**Comment by lbustelo** [comment]
Yep... Bower hell!

**Comment by parente** [comment]
We decided to do the simplest thing for now: package the entire bower_components from the notebook server into the dashboard bundle by copying it in. We'll get more than a particular notebook needs, but there won't be any chance of something mismatching.

While jupyter-incubator/declarativewidgets#25 is open, it might be an opportunity to explore optimizations. I know we've been down the path of separate bower_components before, but maybe that becomes cleaner once urth-import is separate from link.
